### ISSUE TITLE
Remove JDOM Dependency

### ISSUE THREAD

**Issue by benoitx** [Appendium/flatpack#11]
Remove JDOM Dependency. Try a pure JDK implementation.

**Comment by martindiphoorn** [comment]
I just noticed that there is an unit test failing.

```
testInvalidMap(net.sf.flatpack.xml.MapParserTest)  Time elapsed: 0.005 sec
testParseFixedMap(net.sf.flatpack.xml.MapParserTest)  Time elapsed: 0.024 sec
testParseComplexFixedMap(net.sf.flatpack.xml.MapParserTest)  Time elapsed: 0.003 sec  <<< ERROR!
java.lang.NullPointerException
	at java.io.Reader.<init>(Reader.java:78)
	at java.io.InputStreamReader.<init>(InputStreamReader.java:72)
	at net.sf.flatpack.xml.MapParserTest.testParseComplexFixedMap(MapParserTest.java:81)
```

https://travis-ci.org/Appendium/flatpack/builds/400190069?utm_source=github_status&utm_medium=notification

**Comment by martindiphoorn** [comment]
PR: https://github.com/Appendium/flatpack/pull/38
